### ISSUE TITLE
Intended Results

### ISSUE THREAD

**Issue by Inferencer** [Vagver/3DGazeNet#1]
To be clear is this a new approach to the paper [GazeDirector](https://www.youtube.com/watch?v=rSNUGciJH6A) which is used for gaze manipulation
or is this just gaze tracking?

**Comment by eververas** [comment]
Hello,

Our work is about gaze tracking. Instead of only predicting the gaze direction vector as is commonly done, we also regress the 3D coordinates of the eyes which benefits accuracy.

GazeDirector is based on parametric models of the eyes and face and does gaze tracking using optimisation of the shape and texture. Our method performs gaze tracking using direct 3D coordinate regression.
